import sys
sys.stdout.reconfigure(encoding='utf-8')
t = open('C:/Users/Admin/.openclaw/workspace-skills/web-builder/sites/kiem-tra-gia/index.html', 'rb').read().decode('utf-8')
print('=== KIỂM TRA CUỐI (commit cad045c) ===')
print('LANG object:', 'var LANG' in t)
print('__(s) function:', 'function __(s)' in t)
print('switchLang function:', 'function switchLang(l)' in t)
print('Language buttons:', t.count('data-lang='))
print('lang-btn class:', t.count('lang-btn'))
print('data-i18n attrs:', t.count('data-i18n='))
print('__() calls total:', t.count("__(") - t.count("__(s)"))
print('File size:', len(t), 'bytes')
print('localStorage:', 'ktg_lang' in t)
print('\n✅ Hoàn thành!')
print('🌐 GitHub: master@cad045c')
