# The issue: renderPriceTab first reads filter elements BEFORE they exist in DOM
# But the first time it's called, filter elements might not exist yet
# Let's check - the search/specFilter/machineFilter are only created BY renderPriceTab!
# So on first render, they don't exist... 
# Wait, let me check if they're created in the HTML before mainContainer or in the filter bar

import sys
sys.stdout.reconfigure(encoding='utf-8')
with open(r'C:\Users\Admin\.openclaw\workspace-skills\web-builder\sites\kiem-tra-gia\index.html','r',encoding='utf-8') as f:
    d = f.read()

# Find searchInput in HTML (static), not in JS
idx = d.find('searchInput')
if idx >= 0:
    ctx = d[max(0,idx-50):idx+80]
    print(f'searchInput in static HTML: {repr(ctx)}')
else:
    print('searchInput NOT in static HTML')

# Check controlBar - does it contain search/filter?
idx2 = d.find('controlBar')
print(f'\ncontrolBar HTML:')
print(d[idx2:idx2+600])

# Check if filter inputs are in controlBar or generated by renderPriceTab
idx3 = d.find('specFilter')
print(f'\nspecFilter:')
print(d[max(0,idx3-50):idx3+80])
