const http = require('http');
const fs = require('fs');
const path = require('path');

const SITES_DIR = 'C:\\Users\\Admin\\.openclaw\\workspace-skills\\web-builder\\sites';
const DATA_FILE = path.join(SITES_DIR, 'kiem-tra-gia', 'data.js');

// Map hostname + urlPath prefix → subdirectory to serve from
const routes = [
  { host: /doccheck/i, prefix: '/', dir: 'doccheck' },
  { host: /tools/i, prefix: '/kiem-tra-gia', dir: 'kiem-tra-gia' },
  { host: /tools/i, prefix: '/', dir: 'portal' },
];

const mimeMap = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
  '.webp': 'image/webp',
  '.pdf': 'application/pdf',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.txt': 'text/plain; charset=utf-8',
};

function serveFile(res, filePath) {
  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.writeHead(404, { 'Content-Type': 'text/plain; charset=utf-8' });
      res.end('404 Not Found');
      return;
    }
    const ext = path.extname(filePath).toLowerCase();
    res.writeHead(200, { 'Content-Type': mimeMap[ext] || 'application/octet-stream' });
    res.end(data);
  });
}

function findRoute(host, urlPath) {
  for (const r of routes) {
    if (r.host.test(host) && urlPath.startsWith(r.prefix)) return r;
  }
  return null;
}

function parseBody(req) {
  return new Promise((resolve, reject) => {
    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', () => {
      try { resolve(JSON.parse(body)); }
      catch (e) { reject(new Error('Invalid JSON')); }
    });
    req.on('error', reject);
  });
}

const server = http.createServer(async (req, res) => {
  const host = req.headers.host || '';
  let urlPath = req.url.split('?')[0];

  // ====== API: save data to data.js ======
  if (urlPath === '/api/ktg-data' && req.method === 'POST') {
    try {
      const body = await parseBody(req);
      const blocks = body.blocks;

      // Build the data.js content
      let content = '// Auto-generated by DocCheck server\n';
      content += blocks.DATA_PRODUCTS || 'var DATA_PRODUCTS = [];\n';
      content += '\n';
      content += blocks.DATA_BAGS || 'var DATA_BAGS = [];\n';
      content += '\n';
      content += blocks.DATA_OTHERS || 'var DATA_OTHERS = [];\n';
      content += '\n';
      content += blocks.DATA_MAX_LOADING || 'var DATA_MAX_LOADING = {};\n';
      content += '\n';
      content += blocks.DATA_COST_FOB || 'var DATA_COST_FOB = {};\n';

      fs.writeFileSync(DATA_FILE, content, 'utf8');

      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'ok' }));
      console.log('[KTG] Data saved to data.js');
    } catch (err) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ status: 'error', message: err.message }));
      console.error('[KTG] Save error:', err.message);
    }
    return;
  }

  // ====== Static file serving ======
  const route = findRoute(host, urlPath);
  if (!route) {
    res.writeHead(200, { 'Content-Type': 'text/plain; charset=utf-8' });
    res.end('DocCheck server ready');
    return;
  }

  let relativePath = urlPath.slice(route.prefix.length) || '/';
  if (relativePath === '/') relativePath = '/index.html';
  if (!relativePath.startsWith('/')) relativePath = '/' + relativePath;

  const filePath = path.join(SITES_DIR, route.dir, relativePath);

  const realPath = path.resolve(filePath);
  const allowedBase = path.resolve(path.join(SITES_DIR, route.dir));
  if (!realPath.startsWith(allowedBase)) {
    res.writeHead(403, { 'Content-Type': 'text/plain; charset=utf-8' });
    res.end('403 Forbidden');
    return;
  }

  serveFile(res, realPath);
});

server.listen(8080, '0.0.0.0', () => {
  console.log('DocCheck server running on port 8080');
  console.log(`Serving sites from: ${SITES_DIR}`);
  console.log(`Data file: ${DATA_FILE}`);
});
